import re
import json
from nltk.util import ngrams


class RuleClassifier:
    def __init__(self, data, kb_path):
        """
        :param data: dataframe (training or testing)
        :param kb_path: path (knowledge base filepath)
        """
        self.data = data
        # kb key/values split in lexicon and patterns
        self.lexicon = None
        self.patterns = None
        # results appended here
        self.res = []

        with open(kb_path, 'r') as f:
            kb = json.load(f)
            self.lexicon = kb['LEXICON']
            self.pattern = kb['PATTERNS']

    @staticmethod
    def ngram_filter(record, word, n):
        """
        retains only ngrams including a specific word
        :param record: string (dataframe record)
        :param word: string (specific word)
        :param n: int, ngram span
        :return: list of tuples
        """
        tokens = record.split()
        all_ngrams = ngrams(tokens, n)
        filtered_ngrams = [x for x in all_ngrams if word in x]
        return filtered_ngrams

    def get_ngrams(self, text):
        """
        Generates a set of ngrams including the word matched by the pattern
        (if it exists)
        :param text: string (dataframe record)
        :return: list of ngrams
        """
        smoke_reg = re.search('smok\\w+', text)
        if smoke_reg:
            smoke_word = smoke_reg.group(0)
            ngrams = self.ngram_filter(text, smoke_word, 4)
            return ngrams

    def tag_from_context(self, ngrams):
        """
        Applies rules in order to the ngrams generated by a given text
        :param ngrams: list of filtered ngrams
        :return: string (specific label assigned based on rules)
        """
        label = 'Unknown'
        try:
            for ngram in ngrams:
                if any(item in self.lexicon['former'] for item in ngram):
                    label = 'Former Smoker'
                    break
                elif re.search(self.pattern['is_past'], ' '.join(ngram)):
                    label = 'Former Smoker'
                    break
                elif any(item in self.lexicon['ongoing'] for item in ngram):
                    label = 'Smoker'
                    break
                elif re.search(self.pattern['is_present'], ' '.join(ngram)):
                    label = 'Smoker'
                    break
                elif re.search(r'smoked|did smoke', ' '.join(ngram)):
                    label = 'Former Smoker'
                    break
                elif re.search(r'smokes', ' '.join(ngram)):
                    label = 'Smoker'
                    break
                else:
                    label = 'Unknown'
        except TypeError as e:
            print(e)

        return label

    def classify(self, text, row_id):
        """
        Applies some preliminary rules on the full text
        before context matching.
        Appends results to res list
        :param text: string (dataframe record)
        :param row_id: int, id of classified text
        :return: None
        """
        if re.search(r'nonsmoker|does not (\w+\\s)?smoke', text):
            self.res.append((row_id, 'Non Smoker'))
        elif re.search(r'to quit', text):
            self.res.append((row_id, 'Smoker'))
        elif re.search(r'(?<!to\\s)quit|former', text):
            self.res.append((row_id, 'Former Smoker'))
        else:
            ngrams = self.get_ngrams(text)
            label = self.tag_from_context(ngrams)
            self.res.append((row_id, label))
        return
